version: '3.7'

services:
  swarmlet-registry:
    image: registry:2
    restart: always
    environment:
      - REGISTRY_HTTP_ADDR=0.0.0.0:5000
      - REGISTRY_AUTH=htpasswd
      - REGISTRY_AUTH_HTPASSWD_REALM=Registry Realm
      - REGISTRY_AUTH_HTPASSWD_PATH=/basicAuth/security.htpasswd
    volumes:
      - ./:/basicAuth
      - registry-data:/var/lib/registry
    networks:
      - swarmlet-network
      - traefik-public
    deploy:
      mode: global
      labels:
        - traefik.enable=true
        - traefik.tags=traefik-public
        - traefik.docker.network=traefik-public
        - traefik.swarmlet-registry.enable=true
        - traefik.swarmlet-registry.port=5000
        - traefik.swarmlet-registry.frontend.rule=Host:registry.${DOMAIN}
        - traefik.swarmlet-registry.frontend.entryPoints=http,https
        - traefik.swarmlet-registry.frontend.passHostHeader=true
        # - traefik.swarmlet-registry.frontend.headers.SSLRedirect=true
        - traefik.swarmlet-registry.frontend.headers.SSLHost=registry.${DOMAIN}
        - traefik.swarmlet-registry.frontend.headers.STSIncludeSubdomains=true
        - traefik.swarmlet-registry.frontend.headers.STSPreload=true
      placement:
        constraints:
          - node.role == manager

volumes:
  registry-data:

networks:
  swarmlet-network:
    external: true
  traefik-public:
    external: true
