version: "3.7"

services:
  swarmlet-registry:
    image: registry:2
    restart: always
    environment:
      - REGISTRY_HTTP_ADDR=0.0.0.0:5000
      - REGISTRY_AUTH=htpasswd
      - REGISTRY_AUTH_HTPASSWD_REALM=Registry Realm
      - REGISTRY_AUTH_HTPASSWD_PATH=/run/secrets/security.htpasswd
      - REGISTRY_STORAGE_DELETE_ENABLED=true
    volumes:
      - registry-data:/var/lib/registry
    networks:
      - swarmlet-network
      - traefik-public
    secrets:
      - security.htpasswd
    ports:
      - "5000:5000"
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.http.services.registry.loadbalancer.server.port=5000
        - traefik.http.routers.registry.rule=Host(`registry.${DOMAIN}`)
        - traefik.http.routers.registry.entrypoints=http,https
        - traefik.http.routers.registry.middlewares=redirect@file,auth@file
      placement:
        constraints:
          - node.role == manager

volumes:
  registry-data:

networks:
  swarmlet-network:
    external: true
  traefik-public:
    external: true

secrets:
  security.htpasswd:
    external: true
