version: "3.7"

services:
  consul-leader:
    image: consul
    command: agent -server -client=0.0.0.0 -bootstrap -ui
    volumes:
      - consul-data-leader:/consul/data
    environment:
      - CONSUL_BIND_INTERFACE=eth0
      - 'CONSUL_LOCAL_CONFIG={"leave_on_terminate": true}'
    networks:
      - traefik-private
      - traefik-public
    secrets:
      - security.htpasswd
    deploy:
      labels:
        - traefik.frontend.rule=Host:consul.${DOMAIN}
        - traefik.enable=true
        - traefik.port=8500
        - traefik.tags=traefik-public
        - traefik.docker.network=traefik-public
        - traefik.redirectorservice.frontend.entryPoints=http
        - traefik.redirectorservice.frontend.redirect.entryPoint=https
        - traefik.webservice.frontend.entryPoints=https
        - traefik.frontend.auth.basic.usersFile=/run/secrets/security.htpasswd

  consul-replica:
    image: consul
    command: agent -server -client=0.0.0.0 -retry-join="consul-leader"
    volumes:
      - consul-data-replica:/consul/data
    environment:
      - CONSUL_BIND_INTERFACE=eth0
      - 'CONSUL_LOCAL_CONFIG={"leave_on_terminate": true}'
    networks:
      - traefik-private
      - traefik-public
    deploy:
      replicas: ${CONSUL_REPLICAS:-3}
      placement:
        preferences:
          - spread: node.id
      restart_policy:
        condition: on-failure
        delay: 2s
        max_attempts: 5
        window: 120s

  traefik:
    image: traefik:v1.7
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # --constraints=tag==traefik-public
      # Wildcard domain SSL
      # --certificatesResolvers.myresolver.acme.dnsChallenge.provider=digitalocean
      # --certificatesResolvers.myresolver.acme.dnsChallenge.delayBeforeCheck=0
      # ENABLE FOR STAGING
      # --acme.caServer="https://acme-staging-v02.api.letsencrypt.org/directory"
    command: >
      --docker
      --docker.swarmmode
      --docker.watch
      --docker.exposedbydefault=true
      --entrypoints='Name:http Address::80'
      --entrypoints='Name:https Address::443 TLS'
      --consul
      --consul.endpoint="consul-leader:8500"
      --acme
      --acme.email=${EMAIL}
      --acme.storage="traefik/acme/account"
      --acme.entryPoint=https
      --acme.httpChallenge.entryPoint=http
      --acme.onhostrule=true
      --acme.acmelogging=true
      --logLevel=INFO
      --accessLog
      --api
    networks:
      - traefik-private
      - traefik-public
      - swarmlet-network
    secrets:
      - security.htpasswd
    depends_on:
      - consul-leader
    deploy:
      replicas: ${TRAEFIK_REPLICAS:-3}
      placement:
        constraints:
          - node.role == manager
        preferences:
          - spread: node.id
      labels:
        - traefik.frontend.rule=Host:traefik.${DOMAIN}
        - traefik.enable=true
        - traefik.port=8080
        - traefik.tags=traefik-public
        - traefik.docker.network=traefik-public
        - traefik.redirectorservice.frontend.entryPoints=http
        - traefik.redirectorservice.frontend.redirect.entryPoint=https
        - traefik.webservice.frontend.entryPoints=https
        - traefik.frontend.auth.basic.usersFile=/run/secrets/security.htpasswd
      restart_policy:
        condition: on-failure
        delay: 2s
        max_attempts: 5
        window: 120s

  # certdumper:
  #   image: svendowideit/traefik-certdumper:latest
  #   environment:
  #     - CERTDUMPER_MODE=consul
  #     - CERTDUMPER_CONSUL_ADDR=consul-leader:8500
  #   volumes:
  #     - traefik-certs:/traefik/ssl
  #   networks:
  #     - traefik-private
  #   deploy:
  #     mode: replicated
  #     replicas: 1
  #     restart_policy:
  #       condition: on-failure
  #       delay: 60s

volumes:
  consul-data-leader:
  consul-data-replica:
  traefik-certs:
    external: true

networks:
  traefik-private:
  traefik-public:
    external: true
  swarmlet-network:
    external: true

secrets:
  security.htpasswd:
    external: true
